# Generated by Django 6.0.6 on 2026-06-28 06:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_dec',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
