# Generated by Django 6.0.6 on 2026-06-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_title', models.CharField(max_length=50)),
                ('Service_dec', models.TextField()),
            ],
        ),
    ]
